### ISSUE TITLE
MQTT to Service Bus gateway (via AMQP)

### ISSUE THREAD

**Issue by ppatierno** [Azure/connectthedots#119]
Hello,
it could be interesting to develop a gateway (based on .Net Micro Framework) that acts as bridge between MQTT to AMQP (Service Bus).
All messages published on MQTT topics could be forward to corresponding topics on Service Bus.
We could use my M2Mqtt project (https://m2mqtt.wordpress.com/) :-)

Thanks,
Paolo

**Comment by lt72** [comment]
Hi Paolo.

thank you for your interest. I see you are thinking of a NETMF based gateway. That is a great idea. I am also wondering if it would make sense to use the same code that would run on NETMF (or equivalent) to integrate the MQTT-to-AMQP bridge to on R-PI gateway as well, which is written for Mono. 
Several reasons why I am mentioning that: in the first place, if we create a NETMF gateway that support MQTT as the data ingestion protocol, but not AMQP, then we would have two different solutions for two different devices. In theory the code could run cross-platform (C# on Mono for R-Pi and C# on NETMF for any netmf device), so it would be potentially create some confusion.  The job of the gateway in theory is to act as data intake for sensor devices that cannot connect to the cloud, so it would be desirable to have one gateway to expose multiple protocols, rather than one gateway per protocol. 

What are your thoughts?

**Comment by israellot** [comment]
MQTT support on ServiceBus would be really helpful too.

**Comment by ppatierno** [comment]
Hi Lorenzo,
excuse me if I read your reply only now but I had notifications not enabled !
I agree with you ... even if ...

My first idea was to have a client that acts as bridge from MQTT to AMQP because my M2Mqtt client library is cross platform and works well on .Net Micro Framework too.
Now I think (like you) that the better idea could be to have a field gateway (on Pi2 ?) that acts as MQTT broker and republish messages with AMQP to the cloud. In this case, if we decide to use my GnatMQ broker (C# based) it doesn't work on .Net Micro Framework due to generics and LINQ usage. However it works on Pi2 with Mono (Linux) or Windows 10 of course.

What do you think ?

Paolo.

**Comment by lt72** [comment]
That looks like an excellent idea. One way to do it would be to implement an adapter for the CTD gateway, just like the Socket and Serial port adapters, so to speak. Is that what you had in mind?

**Comment by NicoVermeir** [comment]
I'm looking for the same thing. I've setup connect the dots with rpi gateway and I'm using an open source home automation system that exposes sensor values as MQTT messages. I'd like my raspberry pi gateway to pick up those messages and put them in azure through AMQP

**Comment by ppatierno** [comment]
I need to deep into adapters but I think that the first thing to do is to extend my GnatMQ interface (by plugin) to have a way to intercept published messages without the needs to have a client on the gateway.

**Comment by olivierbloch** [comment]
With the switch to IoTHub devices can now talk MQTT directly to Azure. Closing the issue. Feel free to reopen if needed

**Comment by MrTomZed** [comment]
IoT Hub only allows 1 connection per (configured) device. If I have a customer who just wants to send data to my system via MQTT, I can't configure the devices since I don't even know how many there are/will be (maybe it's just a server sending data?). Letting the customer configure the devices in my IoT Hub is also not a reasonable thing to do.
ServiceBus with MQTT support would still be awesome. Otherwise I need a third party tool, correct me if I'm wrong.

**Comment by olivierbloch** [comment]
@MrTomZed , If you don't care about uniquely identifying devices but still want connectivity from devices to go through MQTT then you would want to add a physical gateway on premise or a Cloud gateway that would do identity translation.
Now, if securely connecting devices in a way that limits risks is a requirement, then you can look into the Device Provisioning Service. It allows having a generic configuration on the device and DPS will act as a concierge for the devices that come  in and request credentials to be connected to an IoT Hub.
This project doesn't use DPS as I have not been maintaining it for some time. I will actually indicate in the readme that it is no longer maintained.
