### ISSUE TITLE
PB_setup.md walkthrough does not match PowerBi

### ISSUE THREAD

**Issue by meesern** [Azure/connectthedots#263]
PB_setup.md describes setting up the connection between Azure Stream Analytics and PowerBI but the described steps cannot be followed (in my account at least!).  In particular the line:under heading "
Create a Power BI dashboard" that says 

> "Select a dataset from the Datasets shown in the left nav menu.
> Select "CTDPBIDataSet". This contains the same data as you saw in the CSV file you downloaded above, but in JSON format."

This cannot be followed.  My understanding is that the data set appears only in the 'sreaming datasets' section of the datasets menu and as such cannot be used in the way described here.  Because of this it is impossible to continue to produce the Power BI dashboard as described.

**Comment by olivierbloch** [comment]
Hi @meesern 
It's some time now since I tested this part of the project and its very probable PowerBI changed a couple things in the way the DataSet is exposed. I'll try and go through this and fix the instructions later today or tomorrow.
If you have suggestions, feel free to send over or even send a pull request.
Cheers
Olivier

**Comment by olivierbloch** [comment]
Hi @meesern 
I have updated the PowerBI instructions to reflect changes in IoT Hub, Stream Analytics and PowerBI. You should be able to create a simple line chart showing real time data coming from devices following the new instructions. Let me know if that's not the case.
If that's good enough, feel free to close the issue.
Thanks
